jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Check Dependencies
        run: yarn add google-spreadsheets
      - id: check-deploy
        name: Check Deploy
        run: |
          echo "::set-output name=should-deploy-value::$(yarn should-deploy)"
      - if: steps.check-deploy.outputs.should-deploy-value == 'true'
        name: Dispatch CI
        run: echo "THIS IS WHERE IT WOULD HAPPEN"
    timeout-minutes: 2
on: [push]
# on:
#   schedule:
#     # Run this once at the end of every day
#     - cron: "0 0 * * *"
name: Auto Deploy CI
