jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Check Dependencies
        run: yarn global add google-spreadsheet
      - env:
          GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SPREADSHEET_WORKSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_WORKSHEET_ID }}
        id: check-deploy
        name: Check Deploy
        run: |
          export NODE_PATH=$(yarn global dir)/node_modules
          echo "::set-output name=should-deploy-value::$(node ./scripts/shouldDeploy.js | tail -1)"
      - if: steps.check-deploy.outputs.should-deploy-value != 'true' && steps.check-deploy.outputs.should-deploy-value != 'false'
        run: echo "The check deploy script failed. Check the output." && exit 1
      - if: steps.check-deploy.outputs.should-deploy-value == 'true'
        name: Dispatch CI
        run: echo "THIS IS WHERE IT WOULD HAPPEN"
    timeout-minutes: 2
on: [push]
# on:
#   schedule:
#     # Run this once at the end of every day
#     - cron: "0 0 * * *"
name: Auto Deploy CI
